import httpx

DEFAULT_TIMEOUT = httpx.Timeout(timeout=600.0, connect=5.0)
DEFAULT_MAX_RETRIES = 2
DEFAULT_CONNECTION_LIMITS = httpx.Limits(max_connections=1000, max_keepalive_connections=100)

ENV_OTEL_EXPORTER_OTLP_ENDPOINT = "OTEL_EXPORTER_OTLP_ENDPOINT"

# A2E environment variables
ENV_A2E_PORT = "A2E_PORT"
ENV_A2E_GRPC_PORT = "A2E_GRPC_PORT"
ENV_A2E_HOST = "A2E_HOST"
ENV_A2E_HOST_ROOT_PATH = "A2E_HOST_ROOT_PATH"
ENV_A2E_COLLECTOR_ENDPOINT = "A2E_COLLECTOR_ENDPOINT"
ENV_A2E_CLIENT_HEADERS = "A2E_CLIENT_HEADERS"
ENV_A2E_API_KEY = "A2E_API_KEY"

HOST = "0.0.0.0"
PORT = 6006
